server:
  port: 8080


spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        envers:
          autoRegisterListeners: false

  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true