server:
  port: 8080


spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        envers:
          autoRegisterListeners: false
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: api_kafka_producer
      transaction-topic: transactions


  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true